import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/.wrangler/**',
      // Generated by `wrangler types`.
      'apps/api/worker-configuration.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'separate-type-imports' }],
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      eqeqeq: ['error', 'always'],
      'no-restricted-properties': [
        'error',
        {
          object: 'Math',
          property: 'random',
          message: 'Randomness that affects play must come from the server CSPRNG, passed in as an Rng.',
        },
      ],
    },
  },
  {
    // The rules engine is the one package shared with the browser, so it stays
    // free of platform and runtime dependencies.
    files: ['packages/rules/**/*.ts'],
    rules: {
      'no-restricted-imports': ['error', { patterns: ['@bs/*', 'node:*'] }],
    },
  },
  {
    // The alien fleet's position is the entire secret of the game. The AI
    // package can see both grids, so it must never reach the browser bundle.
    files: ['apps/web/**/*.{ts,tsx}'],
    languageOptions: { globals: globals.browser },
    plugins: { 'react-hooks': reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'no-restricted-imports': [
        'error',
        {
          paths: [{ name: '@bs/ai', message: 'The AI is server-side only; use @bs/protocol types.' }],
        },
      ],
    },
  },
  {
    files: ['apps/api/**/*.ts'],
    languageOptions: { globals: { ...globals.worker, crypto: 'readonly' } },
  },
  {
    files: ['tools/**/*.ts', '**/*.test.ts', 'vitest.config.ts', 'eslint.config.mjs'],
    languageOptions: { globals: globals.node },
    rules: { '@typescript-eslint/no-non-null-assertion': 'off' },
  },
);
