import { API_ROUTES } from '@bs/protocol';
import { CELL_COUNT, HULLS } from '@bs/rules';

/**
 * A machine-readable copy of the same route table the specification documents,
 * for anyone who wants to point a client generator or a schema validator at
 * the API. Emitted as YAML by hand: the document is small, and writing it out
 * avoids a dependency that would exist only for this file.
 */
export function openApiDocument(): string {
  const paths = new Map<string, string[]>();

  for (const route of API_ROUTES) {
    const path = route.path.replace(/:(\w+)/g, '{$1}');
    const parameters = [...path.matchAll(/\{(\w+)\}/g)].map(([, name]) => name);
    const lines = paths.get(path) ?? [];
    lines.push(
      `    ${route.method.toLowerCase()}:`,
      `      summary: ${JSON.stringify(route.summary)}`,
      `      operationId: ${operationId(route.method, path)}`,
      ...(route.auth ? ['      security:', '        - playerToken: []'] : ['      security: []']),
      ...(parameters.length > 0
        ? [
            '      parameters:',
            ...parameters.flatMap((name) => [
              `        - name: ${name}`,
              '          in: path',
              '          required: true',
              '          schema:',
              '            type: string',
            ]),
          ]
        : []),
      ...(route.requestType
        ? [
            '      requestBody:',
            '        required: true',
            '        content:',
            '          application/json:',
            '            schema:',
            `              $ref: '#/components/schemas/${route.requestType}'`,
          ]
        : []),
      '      responses:',
      `        '200':`,
      `          description: ${JSON.stringify(route.responseType)}`,
      '          content:',
      '            application/json:',
      '              schema:',
      `                $ref: '#/components/schemas/${route.responseType}'`,
      ...errorResponses(route.auth, parameters.length > 0),
    );
    paths.set(path, lines);
  }

  return [
    '# Generated by `pnpm docs` from API_ROUTES in @bs/protocol. Do not edit.',
    '# Schemas are named after the TypeScript types in packages/protocol/src/wire.ts,',
    '# which the technical specification embeds in full.',
    'openapi: 3.1.0',
    'info:',
    '  title: Orbital Battleships Command API',
    '  version: 1.0.0',
    '  description: >-',
    '    Server-authoritative Battleship. The alien deployment is never returned',
    '    while a campaign is in progress.',
    'servers:',
    '  - url: /',
    'security:',
    '  - playerToken: []',
    'paths:',
    ...[...paths].flatMap(([path, lines]) => [`  ${path}:`, ...lines]),
    'components:',
    '  securitySchemes:',
    '    playerToken:',
    '      type: apiKey',
    '      in: header',
    '      name: x-player-token',
    '      description: 32-byte hex token issued by POST /api/matches.',
    '  schemas:',
    ...schemas(),
    '',
  ].join('\n');
}

function operationId(method: string, path: string): string {
  const words = path
    .replace(/[{}]/g, '')
    .split('/')
    .filter(Boolean)
    .map((part, index) => (index === 0 ? part : part[0].toUpperCase() + part.slice(1)));
  return method.toLowerCase() + words.map((word) => word[0].toUpperCase() + word.slice(1)).join('');
}

function errorResponses(auth: boolean, addressed: boolean): string[] {
  const lines = [`        '400':`, "          description: 'Malformed request or illegal move'"];
  if (auth) lines.push(`        '401':`, "          description: 'Missing player token'");
  if (addressed) {
    lines.push(`        '403':`, "          description: 'Not your campaign'");
    lines.push(`        '404':`, "          description: 'No such campaign'");
  }
  return lines;
}

/**
 * Hand-written schemas for the wire types. They are checked against the
 * TypeScript definitions by review rather than generation; the specification
 * embeds the definitions verbatim, which remains the normative version.
 */
function schemas(): string[] {
  return [
    '    Placement:',
    '      type: object',
    '      required: [hull, origin, orientation]',
    '      properties:',
    '        hull:',
    '          type: string',
    `          enum: [${HULLS.map((hull) => hull.id).join(', ')}]`,
    '        origin:',
    '          type: integer',
    '          minimum: 0',
    `          maximum: ${CELL_COUNT - 1}`,
    '        orientation:',
    '          type: string',
    '          enum: [horizontal, vertical]',
    '    Shot:',
    '      type: object',
    '      required: [cell, outcome]',
    '      properties:',
    '        cell:',
    '          type: integer',
    '          minimum: 0',
    `          maximum: ${CELL_COUNT - 1}`,
    '        outcome:',
    '          type: string',
    '          enum: [miss, hit, sunk]',
    '        hull:',
    '          type: string',
    '          description: Present only when the outcome is sunk.',
    '    CreateMatchRequest:',
    '      type: object',
    '      required: [difficulty]',
    '      properties:',
    '        difficulty:',
    '          type: string',
    '          enum: [scout, raider, overmind]',
    '        fleet:',
    '          type: array',
    '          description: Optional manual deployment; generated server-side when absent.',
    '          items:',
    "            $ref: '#/components/schemas/Placement'",
    '    FireRequest:',
    '      type: object',
    '      required: [cell]',
    '      properties:',
    '        cell:',
    '          type: integer',
    '          minimum: 0',
    `          maximum: ${CELL_COUNT - 1}`,
    '    MatchView:',
    '      type: object',
    '      description: >-',
    '        The campaign as the player may see it. alienFleet is present only',
    '        once the campaign has finished.',
    '      required: [matchId, difficulty, status, turn, defence, offence, stats, score, log]',
    '      additionalProperties: true',
    '    CreateMatchResponse:',
    '      type: object',
    '      required: [match, playerToken]',
    '      properties:',
    '        match:',
    "          $ref: '#/components/schemas/MatchView'",
    '        playerToken:',
    '          type: string',
    '    ProgressResponse:',
    '      type: object',
    '      required: [progress, rank, recent]',
    '      additionalProperties: true',
    '    ReferenceResponse:',
    '      type: object',
    '      description: Fleet, scoring and doctrine reference data.',
    '      additionalProperties: true',
    '    HealthResponse:',
    '      type: object',
    '      required: [status, version]',
    '      properties:',
    '        status:',
    '          type: string',
    '        version:',
    '          type: string',
    '    ErrorResponse:',
    '      type: object',
    '      required: [error]',
    '      properties:',
    '        error:',
    '          type: string',
  ];
}
